# definition of all form widgets
services:

    # jquery date picker widget
    app_backend.form.jquery_date_type:
        class: App\BackendBundle\Form\Type\JQueryDateType
        tags:
            - { name: form.type, alias: app_backend_form_jquery_date_type }

    # ckeditor widget
    app_backend.form.ckeditor_type:
        class: App\BackendBundle\Form\Type\CKEditorType
        tags:
            - { name: form.type, alias: app_backend_form_ckeditor_type }

    # autocomplete select type
    app_backend.form.autocomplete_type:
        class: App\BackendBundle\Form\Type\AutocompleteType
        tags:
            - { name: form.type, alias: app_backend_form_autocomplete_type }

    # datarenge form type based on https://github.com/dangrossman/bootstrap-daterangepicker
    app_backend.form.date_range_type:
        class: App\BackendBundle\Form\Type\DateRangeType
        tags:
            - { name: form.type, alias: app_backend_form_date_range_type }

    # form type for daterange - displays 3 hidden fields
    app_backend_form_hidden_date_type:
        class: App\BackendBundle\Form\Type\HiddenDateType
        tags:
            - { name: form.type, alias: app_backend_form_hidden_date_type }
